
variables:
  versionbase: 0.1
  increment: $[counter(variables['versionbase'], 1)]
  version: $(versionbase).$(increment)

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "##vso[build.updatebuildnumber]$(version)"
  displayName: 'Set Build Number'

- checkout: self
  displayName: 'Checkout with submodules'
  submodules: true

- task: UseDotNet@2
  displayName: 'Prepare dotnet core'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'Build/*.csproj'
    arguments: '-c Release'
    workingDirectory: 'Build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    projects: 'Build/*.csproj'
    arguments: '-- release'
    workingDirectory: 'Build'

- task: PublishBuildArtifacts@1
  displayName: Publish Binaries Artifact
  inputs:
    pathtoPublish: Output/Binaries
    artifactName: Binaries
    publishLocation: container

- task: PublishBuildArtifacts@1
  displayName: Publish NuGet Artifact
  inputs:
    pathtoPublish: Output/Nuget
    artifactName: NuGet
    publishLocation: container
