name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Checkout submodules
      shell: bash
      run: git submodule update --init --recursive
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Prepare build
      run: dotnet build
      working-directory: ./Build
    - name: Build core projects
      run: dotnet run -- build-core-projects
      working-directory: ./Build
