name: PublishAlpha

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'develop'
        fetch-depth: '0'
    - name: Checkout submodules
      shell: bash
      run: git submodule update --init --recursive
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Prepare build
      run: dotnet build
      working-directory: ./Build
    - name: Build and publish alpha release to nuget
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet run -- publish
      working-directory: ./Build
